### ISSUE TITLE
CSS not work

### ISSUE THREAD

**Issue by danielgis** [gavinr/web-appbuilder-extend-widget-example#1]
Hello, I followed the steps indicated with the InfoSummary widget, but I can't get the CSS to be applied to the html template

https://github.com/gavinr/web-appbuilder-extend-widget-example/blob/b0db5fcb7934720ec8be3ca11dc293c3a05c064e/widgets/CustomEditor/Widget.js#L10

**Comment by gavinr** [comment]
Are you running the grunt task to build the code?

**Comment by danielgis** [comment]
I managed to solve it by copying the CSS file from the existing widget to the new widget created with yeoman. Yes i use GRUNT
